- README.md
> Fix link to TensorFlow website

- test/hello.jl
Hello, it's another one to test Hello TensorFlow without PyCall (https://github.com/malmaud/TensorFlow.jl/pull/2)
thanks!
> added a test for hello

- src/ops.jl
see https://www.tensorflow.org/versions/r0.10/api_docs/python/array_ops.html#split
> Add tf.split operation

- src/ops.jl
- src/ops/math.jl
> add abs op

- src/TensorFlow.jl
- src/core.jl
- src/ops/math.jl
- src/ops/sequences.jl
- src/ops/transformations.jl
- src/py.jl
- src/train/summary_writer.jl
> Fix transpose

- src/core.jl
- src/ops/math.jl
- test/hello.jl
> Wrap more complex/linalg stuff

- src/ops/nn.jl
Hopefully I did **some** of this correctly...
> Wrap way more nn functions

- src/core.jl
- src/shape_inference.jl
- test/hello.jl
This is still in progress as there are further errors, but it at least fixes the first.
> Fix Conv2D shape inference

- src/train/pipeline.jl
> Wrap more batch functions, add docs

- src/ops/summaries.jl
Also clean up `scalar_summary` and its docs.
> Implement audio summary

- src/ops/transformations.jl
- src/shape_inference.jl
- test/hello.jl
> Fix shape calculation shape calculation

- src/ops/rnn_cell.jl
- src/run.jl
> WIP: Revamped `run` code

- src/ops/transformations.jl
It is 1 indexed already but docs were for 0 indexed.
> fix docs for squeeze

- src/core.jl
- test/transformations.jl
> Default source type

- REQUIRE
ref https://github.com/malmaud/TensorFlow.jl/commit/c0962638ca30226587f6ce0b662b997331b2b094
and https://github.com/JuliaLang/Compat.jl/commit/3541c2df0ccf918b97c5d8b5dadd5aa9b1e3f890
> lower Compat requirement to 0.9.5

- src/TensorFlow.jl
- src/ops/math.jl
- src/run.jl
- src/shape_inference.jl
- test/math.jl
- test/shape_inference.jl
had to make a new branch with the batch_matmul
added `squared_difference`
> add two ops

- examples/logistic.jl
- src/core.jl
- src/ops.jl
- src/ops/clipping.jl
- src/ops/image.jl
- src/ops/math.jl
- src/ops/nn.jl
- src/ops/queues.jl
- src/ops/sequences.jl
- src/ops/transformations.jl
- src/shape_inference.jl
- src/train.jl
- src/train/pipeline.jl
> Add convert method

- deps/build_pytensorflow.jl
- src/core.jl
- src/py.jl
- src/train.jl
- test/core.jl
Closes https://github.com/malmaud/TensorFlow.jl/issues/173
> Fix disconnected gradients

- docs/src/addingops.md
This is WIP, as I am not 100% sure on how to link into the docs yet.
This probably should be combined with the Shape Inference docs, and called "Contributing".
Or put together in a section.
I'll be back for this later.
> [WIP] Document how to add an Operation

- src/TensorFlow.jl
- src/io.jl
- src/io/readers.jl
- src/meta.jl
- src/ops/control_flow.jl
- src/ops/math.jl
- src/ops/nn.jl
- src/ops/transformations.jl
- src/train.jl
- src/train/pipeline.jl
- src/variable.jl
I did some regexs to see if @op was missing anywhere.
It was.
Now ,it is in more places than before.
(I am hilarious at naming PRs, really)
> very @op, please nerf

- test/meta.jl
I am trying to reproduce and fix #188 
I can not seem to.
I am guess right now that that issue was tied to having the wrong branch checked out.
These test show that there is no such issue.
> Test against #188

- src/TensorFlow.jl
- src/core.jl
- src/shape_inference.jl
- src/variable.jl
- test/runtests.jl
- test/training.jl
- test/transformations.jl
> Refactor variables

- test/math.jl
In my investigations for #235 
I noted this test was missing.
It can't actually detect #235.
But since I have already written it, I cherry-picked it out of my messing around branch into this PR.
It should marginally improve our coverage.
> missing scatter_sub test

- src/core.jl
- src/ops/rnn_cell.jl
- src/variable.jl
- test/runtests.jl
Most `eltype`s can now be pushed to the type domain.
> Add type parameters

- src/run.jl
- test/run.jl
This fixes #246.
Super simple fix.
I've not tested this against master (it is cherrypicked from my WIP master), so I will let CI do that
> Fixes  #246

- src/ops/summaries.jl
- test/summary.jl
Closes https://github.com/malmaud/TensorFlow.jl/issues/249
> Re-add collections keyword to summary ops

- src/TensorFlow.jl
- src/io.jl
- src/io/tfrecord.jl
- src/py.jl
- test/io.jl
- test/runtests.jl
- test/shape_inference.jl
Closes https://github.com/malmaud/TensorFlow.jl/issues/205
> Add TF record writer tools

- src/ops/nn.jl
- test/nn.jl
> Fix l2_loss

- src/ops/sequences.jl
- src/shape_inference.jl
- test/sequences.jl
> Fix random functions

- src/show.jl
- test/runtests.jl
- test/show.jl
> Check for tensorboard in Conda

- .gitignore
- docs/src/saving.md
- src/train.jl
- test/runtests.jl
- test/train.jl
Example in docs was not running for me.
For a few reasons.
> Ensure save and restore work as per the docs

- .travis.yml
- REQUIRE
Ok, now that we have a new version of Conda that supports this.
We can do this.
Time to double all our testing times.
> Test against Python 2 and Python 3 -- fix #251

- docs/src/logistic.md
> vcat gives an error

- src/py.jl
- test/core.jl
> Make sure error message from Python TensorFlow errors work with python 2 & 3

- src/ops/nn.jl
Minor documentation change.
Because I forget that these things took kwargs only now
> Improve softmax loss docstrings

- src/ops/rnn_cell.jl
- test/nn.jl
> Add forget bias parameter to LSTM cell

- src/core.jl
- src/shape_inference.jl
- src/train.jl
- src/variable.jl
- test/train.jl
> Fixes metagraph importing.

- src/summary_writer.jl
- test/summary.jl
> make FileWriter make directory

- src/ops/indexing.jl
Nothing I like as much as being able to delete a whole pile of ugly code.
This passes all tests, which I believe were pretty comprehensive,
so I believe these changes are thus all fine.
This was much easier than expected.
This is marginally blocking for #221
> Refactor GetIndex to use triangular dispatch

- REQUIRE
- src/ops.jl
- src/ops/comparison.jl
- test/math.jl
Broadcasting has been broken since 0.6 came out.
This implements @MikeInnes 's work around.
> Fix broadcasting

- src/ops/nn.jl
- src/ops/rnn_cell.jl
Put RNN cells in op_name scopes to make visualisations of the graph more readable.
> rnn scopes

- src/shape_inference.jl
- test/shape_inference.jl
shape inference for ArgMax and ArgMin
> register_shape ArgMax ArgMin

- src/shape_inference.jl
- test/shape_inference.jl
> register_shape Select

- src/shape_inference.jl
- test/shape_inference.jl
Shape inference for `max(a,b)` and `min(a,b)`
> shape inference: max, min

- src/ops/rnn_cell.jl
- test/nn.jl
> tf.select on lstm state tuple

- LICENSE.md
@malmaud  we talked about this on slack a few weeks back.
If you are still happy with the idea can you merge this?
> add Lyndon White to copyright line

- deps/build.jl
To simplify some of the weirdness from #396. I'd like to see if this passes CI.
See https://github.com/conda-forge/tensorflow-feedstock/blob/65867e4b0d3d1047e0c44399bbc059ab5e9ca4a8/recipe/meta.yaml#L35
> Simplify build steps as tensorboard is required by tensorflow

- deps/build.jl
> Minor Refactor of build.jl

- src/core.jl
- test/core.jl
I had this lying around locally for a bit. Now that julia 1.0 is supported, it's probably time to include this upstream. Note that this requires grpc support which isn't built into the tensorflow binaries that get installed by this package, so we may have to look at that separately.
> Add basic API for distributed session support

- src/version.jl
Version info wasn't displaying right in 0.7
This should fix that
> fix up version info

- joss_paper/paper.md
> typos in paper

- joss_paper/paper.md
@malmaud , assuming I didn't break any of the citations with this edit, this should be done.
> More paper fixes

- src/core.jl
- test/shape_inference.jl
Closes #466
That was a fiddly one.
> Stop segfaulting when displaying a bunch of controlflow related shapes

- src/core.jl
- test/shape_inference.jl
> Do not break showing the shape of Variables

- deps/build.jl
This has now been released on Conda. Fixes https://github.com/malmaud/TensorFlow.jl/issues/500.
> Updated TF Python version to 1.13.1

- README.md
What do you think @malmaud ?
Are we officially on hiatus here?
> Add Notice about status
