malmaud/TensorFlow.jl

.gitignore
src/show.jl

Just a suggestion; I can tweak this as needed to show the right information in the right places.
I also added the `deps` folder to gitignore wholesale because it was showing me download files that didn't need committing – but let me know if that's mistaken.

Juno Display

---

src/shape_inference.jl

Prior to this I was getting `no method convert(TensorShape, ::Array{Int32})` coming from line 83, so I guess `shape_inferrer` isn't guaranteed to return a `TensorShape`.
After this I'm still seeing an `invalid Array dimensions` error coming from `get_attr` with shape inference – I'll push a fix if I have one.

Fix conversion error

---

.travis.yml

@malmaud you will need to go to codecov.io, sign in using GitHub, and enable coverage tracking for this package. You *don't* need the integration token it gives.

Update travis to do coverage

---

README.md
docs/src/basic_usage.md

That way, the example can be copy pasted, and ran,
without any issues.

replace `@test` with `Base.Test.@test` in first example

---

examples/logistic.jl

Fix the deprecated warning in `examples/logistic.jl`
```
WARNING: exp{T <: Number}(x::AbstractArray{T}) is deprecated, use exp.(x) instead.
```
thanks.

fix deprecated exp, use exp.(x)

---

src/shape_inference.jl

The necessary `+1` on the dimension index seems to be in line with many of the other functions in shape_inference.jl.

Fix shape inference for split #113

---

src/train/pipeline.jl

AFAICT `dynamic_pad` does not work.
[Here](https://www.tensorflow.org/versions/r0.10/api_docs/python/io_ops/input_pipeline#batch) are python docs for what it is meant to do.
I'm not quiet yet familiar enough with the code to make a PR to complete this functionality.

Document `dynamic_pad` and make it throw errors if it used

---

src/ops/nn.jl
src/ops/rnn_cell.jl
src/ops/transformations.jl
src/shape_inference.jl
test/core.jl
test/runtests.jl
test/transformations.jl

unpack was broken for three reasons;
1. if `num` was not provided the path to calculate it used `size` rather than `get_shape`
2. `axis` was 0-based not 1 based (this was also wrong in `pack` so that was fixed too)
3. The way defaulting `num`/`axis` works is not part of the tensor flow operation AFAICT, and need to be done by the wrapper.
In solving 1, i defined a `get_shape(x, dim)` that corresponds to `size(x, dim)`.
And throws exceptions if the shape is unknow or the shape for that axis is unknown.
I then went through and replaces the handful of times this pattern was used.
Arguable the new error message is less clear. But also arguably it is more specific.
If you do not like, you could cherry pick just the first commit.
This is a breaking change, because of the `axis` argument …

Fix Unpack, and refactor to use `get_shape(x, dim)`

---

src/ops/transformations.jl
test/transformations.jl

This allows one to use `squeeze(z)` to automagically get rid of those pesky `1` dimensions.

Give `squeeze` a default dimension, similar to the python API

---

src/ops/nn.jl

`log_poisson_loss` was exported, but not defined.
This causes weirdities when it comes to using reflection and with some code-completion systems.
I added a `@not_implemented` definition, that someone who actually uses it can replace.
(Coincidentally, https://github.com/tensorflow/tensorflow/issues/4097 is the same issue, but in Python)

=Add not_implemented for log_poisson_loss

---

src/ops/transformations.jl
src/shape_inference.jl
test/core.jl
test/runtests.jl
test/shape_inference.jl

This PR fixes shape inference for `concat` and `pack`
- `concat` would fail at inference if a vector with some dimensions unknown was first
- `pack` wouldn't do type inference at all
It also leaves  shape inference for `add_n` wrong, but in a different way.
It is still not broadcasting, but now it gives errors instead of being wrong in broadcast scenarios.
It really wouldn't be too hard to make it correct.
It is just the same generalisation for unification to make a multiargument broadcast.
Which I could do in this PR, or I could do it later seperately.
Also it makes Concat 1 based. Because that was killing me every time I used it.
I guess a deprecation strategy could be employed for that.
Like deprecating concat infavor of cat (which was alway correct).
I put that in it's own commit so …

Improve Shape Inference for things that take lists of Tensors

---

src/ops/transformations.jl
src/shape_inference.jl
test/shape_inference.jl

Now Unpack too can have shape inference.
I am becoming less sure on why one would ever practically use the `num` argument.
Since it means that at this point in the code you know the size of in a particular dimenesion as a julia Int,
but for some reason that value is `unknown` in the TensorShape of your input.
Seems like either the shape inference prior has failed for some reason (and so you would use `reshape` as a ShapeAssert), or you chose not to enter a known shape.
Anyway, it works too.

Make shape inference work for Unpack

---

src/core.jl
src/ops/summaries.jl

This allows you to pass in new collection names into things like summaries, then get them back out with `merge_all_summaries()`.

Be smarter about collections

---

src/core.jl

There is no need to create global variables in Main here.
Ideally there would be away to do this without using `eval` to change scope at all, because that not nice.
But right now i can't see how.

Not using globals to get results from pyproc (minor refactor)

---

src/ops/transformations.jl
test/transformations.jl

I am not 100% sure why, but it seems that when GatherNd is differencated to ScatterNd, the shape comes back as Int32, and the indicies as the type they were on GatherNd.
[ScatterNd](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/scatter-nd) requires that it's shape input and it's gather input have same type.
This fixes that

Fix Gather so its grad can be calculated

---

src/ops/transformations.jl
src/shape_inference.jl
test/shape_inference.jl
test/transformations.jl

ExpandDims now has `get_shape` working.
(Before it just always returned `[Tensor(nothing)]`)
And it has now has 1 based indexing.

=Shape inference and 1-based indexing for ExpandDims

---

README.md
docs/src/index.md

I now have TensorFlow.jl working with CUDA 7.5.
Yay

Mention building from source to get around CUDA version

---

README.md
deps/build.jl
deps/build_libtensorflow.jl
src/core.jl

The two are identical but the former is recommended by the
TensorFlow maintainers and is created in binary releases of
the TensorFlow C library.
The existence of both targets is an unfortunate outcome of tensorflow/tensorflow@783c52e and tensorflow/tensorflow#3830 happening within days of each other.
Note that the TensorFlow C library is now included in binary releases of TensorFlow. The releases are available in URLs of the form:   `https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-TYPE-OS-ARCH-VERSION.tar.gz`. For example:
- CPU-only, Linux, x86_64, 1.0.0: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.0.0.tar.gz
- GPU-enabled, Linux, x86_64, 1.0.0:
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linu …

Use libtensorflow.so instead of libtensorflow_c.so.

---

src/shape_inference.jl
test/shape_inference.jl

This unbreaks `get_shape` for `["Sum", "Prod", "Min", "Max", "All", "Any", "Mean"]`
Which was broken by https://github.com/malmaud/TensorFlow.jl/commit/ec0170e5144cce3d83770f86f4f9ee8b643a09ea#diff-ac236c9f23e3c15683602f303d89d8cdR140
And adds some test cases around that.
and a little refactoring while I had it open

Make TensorShape allowed to be Immuable

---

src/ops/comparison.jl
test/comp.jl

https://github.com/malmaud/TensorFlow.jl/commit/bd28eb2e66cf2f0cbff308a0d6d4165e1fa81cb7 broke it I think.
I've added tests for each infix op, so as to be sure they are all imported still.
This might break 0.6
I'll let TravisCI tell me.

.!= was broken on julia 0.5. 

---

src/ops/rnn_cell.jl

I feel like this was meant to default to -1 rather than 1 ie input_dim=-1.
(rather unexpected break in my code from this change)
regression from 
https://github.com/malmaud/TensorFlow.jl/commit/b7e719742d09c5b1aa66bdb46b6fd68724e71645

Correct default dimension for LSTMCell

---

src/ops/transformations.jl

`Int32`;  `Int32` everywhere.
Everything else is too hard; and honestly not very required.
How often do nets have matrixes that need to be indexed with `Int64`s?
I think many things would break for that already.

Make Scatter_ND enforce type of index/shape

---

src/meta.jl
src/ops/nn.jl
src/ops/rnn_cell.jl
test/nn.jl

This makes the Sequence Length parameter actually do something for Dynamic RNNs.
Also the time-major parameter, while I was here.
I can't think of a nicer way to do this right now.
Though it does seem to have excessive code duplication.
I didn't want to bring the `isa(sequence_length, Void)`, inside the `@tensorflow`.
As I don't think lowering / specialisation on input types  work there.
(Or indeed that it will work within closures, on parameters of the parent type, at all)

Sequence Length for  RNNs working 

---

src/ops/math.jl
test/math.jl

ref #139
Obviously, breaking.
I am still not sure what to do about `argmax` and `argmin`.
My feeling is that they should also be 1 based.
And that everything should be.
Also: you may have noticed, everytime I add a test, I am also sorting that test file into testsets.
It looks nice. and helps identify where it is going wrong.

Make Indmin and Indmax return 1 based results

---

src/ops/indexing.jl
src/ops/transformations.jl
src/show.jl
test/transformations.jl

This PR beings support for slice indexing for `getindex`
Eg `X[1:3,:, 8:end]`
It does not bring the mixed-mode indexing.
though I am starting to have more and more notions of how that would be done.
This is a breaking change as it redefines `Base.length` to do the `Size` op, and `Base.size` to do the `shape` op.
This is, effectively also the strong counter arguement to not-doing https://github.com/malmaud/TensorFlow.jl/issues/102
though now with dynamic `shape`, rather than static `get_shape`
It is required as like `endof(X)` is in linear indexing,
`size(X,dim)` is required in cartesean indexing 
Technically could define `size(X,dim)` without defining `size(X)` to match, but i feel that is more uninituitive, than any other option.
This is requires because it is hardcoded to replace `end` …

Implemented Slicing Indexing (inc end)

---

examples/logistic.jl
src/core.jl
src/run.jl
test/run.jl
test/runtests.jl

No-one would put the wrong size into a placeholder intensionly.
And we already have mechanisms to allow parts of a placeholder to have flexible sizes.
Putting the wrong sized input can render uses of shape inference incorrect.
So we should not let people do it.

Check the sizes of the inputs are compatible with the shapes of the placeholders they fill

---

.gitignore
src/ops/nn.jl
src/shape_inference.jl
test/nn.jl
test/shape_inference.jl

Won't be required much longer once the automatic ops are in, I guess.
But till then; here it is.
Also brings in testsets throughout shape_inference

`softmax_cross_entropy_with_logits` function

---

src/core.jl
src/py.jl
test/core.jl

Solves #212
Possible issue with implementation `node_name` is now applied element-wise to `AbstractVectors`.
It makes the implementation short and simple but I'm not sure how I feel about it

Allow more options for Gradient calculation

---

.gitignore
README.md
src/ops/transformations.jl
test/transformations.jl

does #187
So that cool.
This could do with some code review (like all code).
It contains a `@goto` which is frowned upon by Dijkstra.
Normally I want to use gotos to break out of nested loops, and then I immediately see that I want to refactor to be using a function and then can use return to breakout.
But this time I want to restart the loop from the beginning
One option would be to use a while loop and manage the index manually
But I don't think that is more readable.
One thing that is still pending is a general way for this to be dispatched to when one or more of the varargs is an `AbstractTensor` and one or more is not (but assumably can be converted).
Right now this is accomplished by specialcasing the first two arguments.
So long as one of the first two arguments is an …

[A; B] and [A B] concatenation syntax (#187)

---

src/ops/nn.jl

I was really confused as to why passing a single tensor to static rnn was working, when it expects a Vector of Tensors.
It was like there was an undocumented feature.
then I look in the code, and I find that yes, such a feature exists and is undocumented
Then I look at git blame and find who created that feature and it was me.
So here as some basic docs.

Document overload for static `rnn` that takes a single Tensor

---

src/ops.jl
src/ops/math.jl

avoid breaking the package on early dev versions, in case bisecting
on base is ever needed to isolate a bug triggered by this package

be more specific about VERSION cutoffs in ops.jl

---

src/ops/sequences.jl
test/nn.jl

>The new imported op has a different signature:
and does not support minval, maxval or dtype.
random_uniform(shape; seed=0, seed2=0)
This brings back old-functionality. So that `dropout` isn't broken anymore.
I'm not sure what is meant in the TODO about using global seed.
Does that mean something like 
`seed1=Base.Random.GLOBAL_RNG.seed |> first` ?

Fix the uniform_random used by dropout

---

src/ops/math.jl
test/math.jl

This wraps up the 
I am surprised at how poor the reconstruction error from the Tensorflow result is
I  found in one test 
- the  julia error at 4.346551f-12
- and the tensorflow error at 1.1636697f-10
Thus the factor of 100 in checking the error value.
Julia just [wraps LAPACK `gesdd!`]https://github.com/JuliaLang/julia/blob/bc606f6cc8bc6127979d90c6ccb239b2e2a14448/base/linalg/svd.jl#L28)
I am going to investigate further if there is actually a difference in accuracy of it it was just some bad luck for a particularly ill conditioned matrix in some sense.
But if I find anything wrong it is an upstream issue, anyway.
@alha02

add SVD binding re: #218

---

REQUIRE
deps/build.jl
deps/build_pytensorflow.jl

The number of dependencies we have is huge. (see https://juliaobserver.com/packages/TensorFlow for upstream)
This cuts it down a little.
Biggest change being to get rid of Requests.jl, and just use `Base.download` in the build.jl.
This should knock out maybe 5 or more further upstream requirements.
This also gets rid of a couple of other requirements, that are not used at all.
Other packages maybe that could be shed:
-  Juno.jl
- only used for a small amount of improved `show`
- this would also get rid of the indirect Hiccup.jl and Media.jl, requirement
- I think we should keep this; hopefully optional packages will come in soon (lots of discussion going around there)
- Distributions.jl
- This would knock out about 8 upstream dependencies
- I don't think we do much with it that couldn't …

Reduce the number of dependancies

---

README.md
docs/src/build_from_source.md

After the discussion in Issue #220, I figured it'd make sense to write a documentation page on building from source. Currently, the information needed for everything to work is scattered in between TensorFlow documentation pages and various issues on this repo.
It would be great to add some information about the binary patch in #245 so that users may incorporate it. That way potential segfaults and unexpected behavior are avoided.

Added documentation for building from source (with or without GPU support)

---

src/core.jl
src/ops/indexing.jl
src/ops/nn.jl
src/ops/rnn_cell.jl
src/ops/sequences.jl
src/ops/transformations.jl
src/shape_inference.jl
test/core.jl
test/nn.jl
test/shape_inference.jl
test/transformations.jl

The main thrust of this PR is to allow the batch_size of a RNN input to be able to be unknown.
So it can be 
for a static RNN eg
```
data = placeholder(Float32; shape=(-1,20, 25)
```
And for a dynamic RNN eg:
```
data = placeholder(Float32; shape=(-1,-1, 25)
```
The PR does a few other things/
- I found that time-major actually didn't work as a parameter (Might need to add a test for that still, though I have checked it manually)
- It was too easy to do illegal sliced indexing and get stackoverflows (see https://github.com/MikeInnes/Flux.jl/pull/28#issuecomment-301220635)
- TensorShape was messing up on a cornercase that showed up in testing Transpose. So I tweaked it and added tests
This could be broken into 4 PR. for commits 2,3,4,(1+5).
Technically, I think they would each work on …

Make RNNs not need batch size to be statically known

---

deps/build.jl

Trivial change.
I mistakenly had `use_gpu` as a `const` variable.
But it is modified, if you are on Mac, and say you want to use the GPU.
It will work fine, but give a warning.

use_gpu is not const

---

src/core.jl

I can never remember the names for these.
So I documented them.
and included cross references.
I did not include references to `set_def_graph` as that is not exported.
Presumably because we would rather people used `as_default`

Document default graph changing functions

---

src/core.jl

I think this was missed when changing the kwarg value to `:backend`.
in #281

Check backend version against python client version

---

deps/build.jl

Should fix #292 
see that issue for why we don't need tensorflow-gpu even to use GPU.

Don't try and use the GPU python package

---

test/shape_inference.jl

In the course of chasing down another issue,
I wanted to be sure it wasn't dropout failing shape inference.
Indeed dropout is not failing shape inference,
and now we have tests to prove it.

Add a check that dropout has working shape inference

---

REQUIRE
src/ops/nn.jl
test/nn.jl

Close #298
Possible issue with softmax.
Tensorflow operates per row on matrix.
StatsFuns operates on the whole matrix
```julia
julia> run(Session(), nn.softmax(x))
4×4 Array{Float64,2}:
0.182344  0.176948  0.312947  0.327761
0.34033   0.152795  0.170746  0.336128
0.284187  0.273225  0.219796  0.222792
0.177648  0.349585  0.238929  0.233839
julia> softmax(x)
4×4 Array{Float64,2}:
0.0428782  0.0416093  0.0735896  0.077073 
0.0928664  0.0416934  0.0465917  0.0917197
0.0774796  0.0744908  0.0599243  0.0607409
0.0389658  0.0766791  0.0524073  0.0512909
```

Make statsfuns compatible #298

---

src/ops/control_flow.jl
test/control.jl
test/init_ops.jl
test/runtests.jl

I'm pretty sure this used to be the case.
It was useful because adding an identity node can be used to easily give an pseudo-operation a name in the graph.
Eg the output of `gradients` is not intrinsically named.
Also while I was at it I cleaned up a few tests.
Perhaps most interestingly I spotted that `test/init_ops.jl` was not being run by `runtests`

Make identity overload Base.identity

---

src/core.jl
src/ops/control_flow.jl
test/breaklibtensorflow.jl
test/minimal_breaking_example.jl

I'm not longer certain that https://github.com/tensorflow/tensorflow/issues/8669 is actually an upstream issue.
At least not in the form we see it most often -- the while_loop
My MWE is:
```julia
using TensorFlow
sess = Session(Graph())
i = constant(1)
end_i = TensorFlow.while_loop((i->i <= 10), i->i+1, [i])
```
Giving: 
```
Tensorflow error: Status: Input 0 ('Const') for 'while/Enter' was not previously added to ShapeRefiner.
```
But actually this can be reproduced more simply via:
```julia
sess=Session(Graph())
j=constant(31)
g=Graph()
c_o=as_default(g) do
c = 2*j
end
```
giving: 
```
Tensorflow error: Status: Input 1 ('Const') for 'Mul' was not previously added to ShapeRefiner.
```
Because that is basically what is happening.
We are creating a new graph, 
and then referring to nodes in …

[WIP] Handle difficulties relating to while_loop

---

src/run.jl
src/shape_inference.jl
test/shape_inference.jl

Was trying out the [image recognition tutorial](https://www.tensorflow.org/tutorials/image_recognition) a had some issues with the string tensor. I'm new to TensorFlow but I think these changes are necessary to get the right behavior for string tensors. At least it was necessary for the tutorial code to work and I think the intermediate results are similar to the Python version. Do you handle string tensor in a special way in this package?

Make String tensors scalar like

---

src/ops/clipping.jl

I noticed there is a `.^2.0` which would always produce `Float64`. Not sure if this is the best way to deal with it but let me know otherwise.

squaring of global_norm adaptive to data type

---

src/train.jl
test/train.jl

I think this PR follows the original intent of the function and that `sort!` call was accidentally omitted.
Example of what this commit changes. Let's say we're saving checkpoints named
```
1
2
3
4
5
6
7
8
9
10
11
```
With `max_to_keep=5` we would expect only 7,8,9,10,11 to remain. But 10 and 11 are lexicographically sorted before 2 so (at least on OS X) `readdir` gives the following list:
```
1
10
11
2
3
4
5
6
7
8
9
```
And we'll only keep: 5, 6, 7, 8, 9 and we'll discard the last checkpoints that was saved most recently.
The solution is to not rely on the order from `readdir` and call `sort!` on the versioned checkpoints.

saver.max_to_keep needs to sort versions before discarding old versions

---

src/shape_inference.jl
test/shape_inference.jl

shape inference of `identity(x)` and tests of shape inference for simple 1-input 1-output functions

shape of identity(x)

---

src/ops/rnn_cell.jl

It was just wrong AFAICT
Sigmoid inside a tanh is basically the same as replacing the tanh with a sigmoid.
So it may actually have had meaningful effect.
Though I don't think so, I believe from the GRU design that that variable (which I think of as potential new state), really can have any choice of activation functions.
Unlike the gates which are constrained by the design.
Still the traditional activation function is `tanh`  there.

Remove extra sigmoid from GRU

---

src/core.jl
test/core.jl

Turn's out `haskey(graph, node_name)` was always wrong but no one noticed.
This fixes it and adds tests

Fix haskey

---

src/generate_ops.jl
test/ops.jl

I wanted to be able to do 
`import_op("Atan2")` and have that work as `Ops.atan2`.
This makes that possible.
Only change really was to make it use `names` to check, rather than `isdefined`.
Hard part was getting the tests to work because https://github.com/JuliaLang/julia/issues/27244

Add ability to import names that are already used in Base

---

deps/build.jl

Getting the following error message during `Pkg.build("TensorFlow")` on `v0.9.0`
```
Warning: 'conda-forge' already in 'channels' list, moving to the top
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:
- tensorflow=1.7.0
```
I can't find 1.7.0 on [anaconda.org/conda-forge](https://anaconda.org/conda-forge/tensorflow/files) either. But it does have `tensorflow=1.8.0`.
However the 1.8.0 package doesn't seem to install `numpy` as it should. I'm getting this message:
```
julia> pyimport("tensorflow")
...
pyimport sais ImportError('No module named numpy',)
...
```
Installing numpy explicitly seems to do the trick.

conda-forge doesn't have tensorflow=1.7.0, but it does have 1.8.0

---

src/core.jl

Fixes comment from https://github.com/malmaud/TensorFlow.jl/issues/400#issuecomment-395952667
@colbec 
>My mistake was in thinking that Julia would be able to evaluate the tilde for the home directory.
Replacing the tilde with the full "/home/..." resolved that issue.
But the comment about AVX2 and FMA remains. I'm looking into it.
idk, if this is the right thing to do or not.
On the one-hand: I see no downsides, on the other-hand I'm aware a lot of programs do not do this. So maybe there is a reason?
This does not currently have tests. We could make tests only awkwardly.
We'ld need to move the file and start a new julia session.
(I think we might start a new julia session for some tests? I feel like I've done it before.)
c.f.: https://github.com/JuliaLang/julia/issues/24152
--> …

Expand tilde when looking for LIBTENSORFLOW

---

docs/src/build_from_source.md

as we've gotten ride of them for now, and if we bring them back it will be with a solution that does not require custom patched libtensorflow

Remove stuff from docs about getting dynamic RNNs working with custom libtensorflow

---

ISSUE_TEMPLATE.md
src/TensorFlow.jl
src/core.jl
src/version.jl
test/runtests.jl

This is to help with making it easier to process issues.
Basically the user can run `tf_versioninfo()` and it outputs basically all the info that might possibly be relevant.
Some of the info will be irrelevant, like checking the `pip --version` if it was installed with Conda.
But I figured it is easier just ignore the irrelevant parts.
Alternatively, it could be made slightly more complex and avoid including things that probably don't matter.
But it is kind of hard to tell what interesting setups people might be using.
Example output:
```
julia> tf_versioninfo()
Please copy-paste all this info into any bug reports.
Note that this may display some errors. But not all errors are bad. Some are expected
----------------
Library Versions
----------------
tf_version(kind=:backend) = v"1.7.0" …
```

Add a versionoinfo function that dumps out all the info needed for debugging

---

src/ops/nn.jl

behaves the same way as `max_pool`

added avg_pool

---

src/ops/indexing.jl

I know this was fixed. in julia 0.7

Remove out-of-date comment

---

src/meta.jl
src/ops/indexing.jl
test/meta.jl

This is needed,
as different methods (with different argument types) may or may not support the name kwarg,
and we only want to insert it for ones that do.
Conveniently since the traits are built on dispatch already it is only a small change,
Closes #448 
Those  it turns out that the problem in #448, re the use of `:`
actually is unrelated to the main thrust of this PR:
`TensorRange` doesn't take a `name` kwarg,
and so the `:` overloads shouldn't actually have been declared with `@op` at all.
But a different bug actually prevented that being visible in 0.6,

Make the autoname inserting a function of the argument types

---

docs/src/build_from_source.md

In Julia 1.0 you will likely have multiple TensorFlow directories and it is actually really hard to workout which is being used.
so using the environment variable should be preferred.

Update building from source docs

---

src/core.jl

This is needed for our XLA work, so that we can ensure that the device a
tensor is coming fron matches the device a model is running on.

Add equality overrides for `Device` and `DevicePart`

---

src/core.jl

The lack of `Cint` for the second to last argument is particularly problematic, because TensorFlow would get incorrect values for the lengths of the shape array.

Fix types in set_attr_shape_list

---

joss_paper/paper.bib
joss_paper/paper.md

Re:
https://github.com/openjournals/joss-reviews/issues/1002#issuecomment-435657358

Fix a few last issues with the paper

---

src/ops/math.jl
test/meta.jl

As is, it errors because of the `name` keyword when used with `@tf`.

Make unary "-" work with @tf

---

src/version.jl

Before 
```
-------------
Python Status
-------------
PyCall.conda = true
Trying to evaluate ENV["PYTHON"] but got error: KeyError("PYTHON")
PyCall.PYTHONHOME = /Users/oxinabox/.julia/conda/3:/Users/oxinabox/.julia/conda/3
String(read(#= /Users/oxinabox/Documents/talks/JuliaDeepLearningMeetupLondon2019/dev/Te
nsorFlow/src/version.jl:105 =# (Core.:(@cmd))("pip --version"))) = pip 18.1 from /usr/l
ocal/lib/python2.7/site-packages/pip (python 2.7)
String(read(#= /Users/oxinabox/Documents/talks/JuliaDeepLearningMeetupLondon2019/dev/Te
nsorFlow/src/version.jl:106 =# (Core.:(@cmd))("pip3 --version"))) = pip 18.1 from /usr/
local/lib/python3.7/site-packages/pip (python 3.7)
```
after
```
-------------
Python Status
-------------
PyCall.conda = true
Trying to evaluate ENV["PYTHON"] but got error: …
```

avoid displaying cmd objects in tf_version_info
